[package]
name = "niao_pkg"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
niao_crypto = { workspace = true }
niao_http = { workspace = true }
niao_archive = { workspace = true }
niao_json_core = { workspace = true, features = ["serde"] }

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
