[package]
name = "niao_pkg"
version.workspace = true
edition.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
niao_crypto = { workspace = true }
niao_http = { workspace = true }
niao_archive = { workspace = true }

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
