//! Typed Niao client stub generation (~openapi-generator niao target).

use crate::doc::OpenApiDoc;
use crate::error::{OpenApiError, OpenApiResult};
use crate::pathutil::{method_key, normalize_path};
use serde_json::{Map, Value};

#[derive(Debug, Clone)]
pub struct ClientStubOpts {
    pub module_name: String,
    pub base_url: String,
    pub client_var: String,
    pub include_types: bool,
}

impl Default for ClientStubOpts {
    fn default() -> Self {
        Self {
            module_name: "api_client".into(),
            base_url: "".into(),
            client_var: "client".into(),
            include_types: true,
        }
    }
}

impl ClientStubOpts {
    pub fn from_map(m: Option<&Map<String, Value>>) -> Self {
        let mut o = Self::default();
        if let Some(m) = m {
            if let Some(s) = m.get("module").and_then(|v| v.as_str()) {
                o.module_name = s.to_string();
            }
            if let Some(s) = m.get("module_name").and_then(|v| v.as_str()) {
                o.module_name = s.to_string();
            }
            if let Some(s) = m.get("base_url").and_then(|v| v.as_str()) {
                o.base_url = s.to_string();
            }
            if let Some(s) = m.get("client_var").and_then(|v| v.as_str()) {
                o.client_var = s.to_string();
            }
            if let Some(b) = m.get("include_types").and_then(|v| v.as_bool()) {
                o.include_types = b;
            }
        }
        o
    }
}

/// Emit a Niao source file that wraps `http` calls for each operation.
pub fn client_stub(doc: &OpenApiDoc, opts: &ClientStubOpts) -> OpenApiResult<String> {
    let mut out = String::with_capacity(4096);
    out.push_str("// Auto-generated by nopenapi — do not edit by hand.\n");
    out.push_str("// Typed HTTP client stub (~openapi-generator).\n\n");
    out.push_str("import \"http\"\n\n");

    let title = doc
        .root
        .get("info")
        .and_then(|i| i.get("title"))
        .and_then(|t| t.as_str())
        .unwrap_or("API");
    out.push_str(&format!("// Client for: {title}\n"));
    out.push_str(&format!(
        "let {var}_base = \"{base}\"\n\n",
        var = opts.client_var,
        base = escape_str(&opts.base_url)
    ));

    if opts.include_types {
        if let Some(schemas) = doc
            .root
            .get("components")
            .and_then(|c| c.get("schemas"))
            .and_then(|s| s.as_object())
        {
            out.push_str("// --- Schema notes ---\n");
            let mut names: Vec<&String> = schemas.keys().collect();
            names.sort();
            for name in names {
                out.push_str(&format!(
                    "// schema {name}: see OpenAPI components.schemas.{name}\n"
                ));
            }
            out.push('\n');
        }
    }

    out.push_str(&format!("fn make_{}(base) {{\n", opts.module_name));
    out.push_str("    if base == nil { base = \"\" }\n");
    out.push_str("    {\n");
    out.push_str("        base: base,\n");

    let ops = collect_ops(doc)?;
    for op in &ops {
        out.push_str(&format!("        {}: {}_impl,\n", op.fn_name, op.fn_name));
    }
    out.push_str("    }\n}\n\n");

    for op in &ops {
        out.push_str(&format!("fn {}_impl(self", op.fn_name));
        for p in &op.path_params {
            out.push_str(", ");
            out.push_str(p);
        }
        if op.has_query {
            out.push_str(", query");
        }
        if op.has_body {
            out.push_str(", body");
        }
        out.push_str(", opts) {\n");
        out.push_str("    if opts == nil { opts = {} }\n");
        out.push_str(&format!(
            "    let path = {}\n",
            render_path_expr(&op.path_template, &op.path_params)
        ));
        out.push_str("    let url = self.base + path\n");
        if op.has_query {
            out.push_str("    if query != nil {\n");
            out.push_str("        // caller may pass a query string or object-serialized form\n");
            out.push_str("        url = url + \"?\" + query\n");
            out.push_str("    }\n");
        }
        match op.method.as_str() {
            "get" => {
                out.push_str("    return http.get(url, opts)\n");
            }
            "delete" => {
                out.push_str("    return http.delete(url, opts)\n");
            }
            "post" | "put" | "patch" => {
                let verb = &op.method;
                if op.has_body {
                    out.push_str(&format!("    return http.{verb}(url, body, opts)\n"));
                } else {
                    out.push_str(&format!("    return http.{verb}(url, nil, opts)\n"));
                }
            }
            other => {
                out.push_str(&format!("    // method {other}: use http.request\n"));
                out.push_str(&format!(
                    "    return http.request(\"{}\", url, nil, opts)\n",
                    other.to_ascii_uppercase()
                ));
            }
        }
        out.push_str("}\n\n");
    }

    out.push_str(&format!(
        "let {} = make_{}({}_base)\n",
        opts.client_var, opts.module_name, opts.client_var
    ));
    Ok(out)
}

struct OpInfo {
    fn_name: String,
    method: String,
    path_template: String,
    path_params: Vec<String>,
    has_query: bool,
    has_body: bool,
}

fn collect_ops(doc: &OpenApiDoc) -> OpenApiResult<Vec<OpInfo>> {
    let mut out = Vec::new();
    let Some(paths) = doc.root.get("paths").and_then(|v| v.as_object()) else {
        return Ok(out);
    };
    let methods = [
        "get", "post", "put", "delete", "patch", "options", "head", "trace",
    ];
    let mut path_keys: Vec<&String> = paths.keys().collect();
    path_keys.sort();
    for path in path_keys {
        let Some(item) = paths.get(path).and_then(|v| v.as_object()) else {
            continue;
        };
        for m in methods {
            let Some(op) = item.get(m).and_then(|v| v.as_object()) else {
                continue;
            };
            let method = method_key(m)?;
            let id = op
                .get("operationId")
                .and_then(|v| v.as_str())
                .map(|s| sanitize_fn(s))
                .unwrap_or_else(|| {
                    sanitize_fn(&format!(
                        "{}_{}",
                        method,
                        path.trim_matches('/').replace('/', "_")
                    ))
                });
            let path_params = crate::pathutil::path_params(path);
            let has_query = op
                .get("parameters")
                .and_then(|v| v.as_array())
                .map(|a| {
                    a.iter()
                        .any(|p| p.get("in").and_then(|x| x.as_str()) == Some("query"))
                })
                .unwrap_or(false);
            let has_body = op.get("requestBody").is_some()
                || matches!(method.as_str(), "post" | "put" | "patch");
            out.push(OpInfo {
                fn_name: id,
                method,
                path_template: normalize_path(path),
                path_params,
                has_query,
                has_body: has_body && matches!(m, "post" | "put" | "patch"),
            });
        }
    }
    // ensure unique fn names
    let mut seen = std::collections::HashMap::<String, usize>::new();
    for op in &mut out {
        let n = seen.entry(op.fn_name.clone()).or_insert(0);
        *n += 1;
        if *n > 1 {
            op.fn_name = format!("{}_{}", op.fn_name, *n);
        }
    }
    Ok(out)
}

fn sanitize_fn(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for ch in s.chars() {
        if ch.is_ascii_alphanumeric() {
            out.push(ch);
        } else {
            out.push('_');
        }
    }
    if out.is_empty() {
        "op".into()
    } else if out.as_bytes()[0].is_ascii_digit() {
        format!("op_{out}")
    } else {
        out
    }
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn render_path_expr(template: &str, params: &[String]) -> String {
    // Build: "/users/" + id + "/posts"
    if params.is_empty() {
        return format!("\"{}\"", escape_str(template));
    }
    let mut expr = String::from("\"\"");
    let mut rest = template;
    for p in params {
        let needle = format!("{{{p}}}");
        if let Some(idx) = rest.find(&needle) {
            let before = &rest[..idx];
            if !before.is_empty() {
                expr.push_str(&format!(" + \"{}\"", escape_str(before)));
            }
            expr.push_str(&format!(" + {p}"));
            rest = &rest[idx + needle.len()..];
        }
    }
    if !rest.is_empty() {
        expr.push_str(&format!(" + \"{}\"", escape_str(rest)));
    }
    // strip leading `"" + `
    if let Some(stripped) = expr.strip_prefix("\"\" + ") {
        stripped.to_string()
    } else {
        expr
    }
}

/// Convenience: generate stub or error string via OpenApiError.
pub fn client_stub_str(
    doc: &OpenApiDoc,
    opts_map: Option<&Map<String, Value>>,
) -> OpenApiResult<String> {
    let opts = ClientStubOpts::from_map(opts_map);
    if doc
        .root
        .get("paths")
        .and_then(|v| v.as_object())
        .map(|m| m.is_empty())
        .unwrap_or(true)
    {
        return Err(OpenApiError::new(
            "client_stub: document has no paths — nothing to generate",
        ));
    }
    client_stub(doc, &opts)
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn generates_get() {
        let doc = OpenApiDoc::parse_value(json!({
            "openapi": "3.1.0",
            "info": {"title": "T", "version": "1"},
            "paths": {
                "/users/{id}": {
                    "get": {
                        "operationId": "getUser",
                        "parameters": [
                            {"name": "id", "in": "path", "required": true, "schema": {"type": "string"}}
                        ],
                        "responses": {"200": {"description": "ok"}}
                    }
                }
            }
        }))
        .unwrap();
        let s = client_stub_str(&doc, None).unwrap();
        assert!(s.contains("fn getUser_impl"));
        assert!(s.contains("http.get"));
        assert!(s.contains("+ id"));
    }
}
