use crate::error::ProtoResult;
use crate::schema::{MessageInfo, ProtoSchema};

/// Options controlling Niao source codegen from a schema.
#[derive(Debug, Clone, Default)]
pub struct CodegenOptions {
    pub module_name: Option<String>,
    pub include_helpers: bool,
}

/// Generate Niao helper source for all messages in a schema.
pub fn codegen(schema: &ProtoSchema, opts: &CodegenOptions) -> ProtoResult<String> {
    let module = opts
        .module_name
        .clone()
        .unwrap_or_else(|| "generated_proto".to_string());
    let mut out = String::new();
    out.push_str(&format!("// Generated by nproto.codegen — do not edit.\n"));
    out.push_str(&format!("// Module: {module}\n\n"));
    out.push_str("import \"nproto\"\n\n");
    if let Some(file) = schema.fds.file.first() {
        if let Some(pkg) = &file.package {
            out.push_str(&format!("// package {pkg}\n\n"));
        }
    }
    for name in schema.message_names() {
        let info = schema.describe_message(&name)?;
        emit_message(&mut out, &name, &info, opts.include_helpers);
        out.push('\n');
    }
    for name in schema.enum_names() {
        let desc = schema.enum_descriptor(&name)?;
        out.push_str(&format!("// enum {name}\n"));
        for val in desc.values() {
            out.push_str(&format!(
                "let {}_{} = {}\n",
                desc.name(),
                val.name(),
                val.number()
            ));
        }
        out.push('\n');
    }
    Ok(out)
}

fn emit_message(out: &mut String, full_name: &str, info: &MessageInfo, helpers: bool) {
    let short = full_name.rsplit('.').next().unwrap_or(full_name);
    out.push_str(&format!("// message {full_name}\n"));
    for field in &info.fields {
        out.push_str(&format!(
            "//   {} {} = {} [{}]\n",
            field.label, field.kind, field.number, field.name
        ));
    }
    if helpers {
        out.push_str(&format!(
            "fn new_{short}(schema, fields) {{\n    return nproto.new_message(schema, \"{full_name}\", fields)\n}}\n"
        ));
        out.push_str(&format!(
            "fn decode_{short}(schema, bytes) {{\n    return nproto.decode(schema, \"{full_name}\", bytes)\n}}\n"
        ));
        for field in &info.fields {
            out.push_str(&format!(
                "let FIELD_{}_{} = \"{}\"\n",
                short.to_uppercase(),
                field.name.to_uppercase(),
                field.name
            ));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::compile::compile_source;

    #[test]
    fn emits_helpers() {
        let src = r#"syntax="proto3"; package g; message Item { int32 id = 1; }"#;
        let schema = compile_source("i.proto", src, &[]).unwrap();
        let code = codegen(
            &schema,
            &CodegenOptions {
                include_helpers: true,
                ..Default::default()
            },
        )
        .unwrap();
        assert!(code.contains("new_Item"));
        assert!(code.contains("FIELD_ITEM_ID"));
    }
}
