[package]
name = "niao_bytecode"
version.workspace = true
edition.workspace = true

[dependencies]
niao_ast = { workspace = true }
niao_ir = { workspace = true }
niao_runtime = { workspace = true }
serde = { workspace = true }
niao_json_core = { workspace = true, features = ["serde"] }

[dev-dependencies]
niao_parser = { workspace = true }
